//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45_Team10a_LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookBorrowAnalysi
    {
        public string MemberCategory { get; set; }
        public int MemberID { get; set; }
        public System.DateTime DateBorrow { get; set; }
        public Nullable<int> NoOfTransaction { get; set; }
    }
}
