//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45_Team10a_LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookListing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookListing()
        {
            this.BookAdjustments = new HashSet<BookAdjustment>();
            this.IssueTrans = new HashSet<IssueTran>();
        }
    
        public string BookID { get; set; }
        public string ISBN { get; set; }
        public string BookTitle { get; set; }
        public string BookType { get; set; }
        public string Language { get; set; }
        public string AuthorID { get; set; }
        public string PublisherID { get; set; }
        public int TotalStock { get; set; }
        public int NumberLoaned { get; set; }
        public string Section { get; set; }
        public string CallNumber { get; set; }
        public string Notes { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAdjustment> BookAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueTran> IssueTrans { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
