//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45_Team10a_LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAdjustment
    {
        public string BookID { get; set; }
        public int AdjustmentQty { get; set; }
        public System.DateTime DateAdjust { get; set; }
        public int WhoAdjust { get; set; }
        public string AdjustmentReason { get; set; }
    
        public virtual BookListing BookListing { get; set; }
        public virtual Librarian Librarian { get; set; }
    }
}
