//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45_Team10a_LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookList
    {
        public string BookID { get; set; }
        public string BookTitle { get; set; }
        public string ISBN { get; set; }
        public string BookType { get; set; }
        public string AuthorName { get; set; }
        public string PublisherName { get; set; }
        public int TotalStock { get; set; }
        public int NumberLoaned { get; set; }
    }
}
